import type { Item } from "../engine/types";
import { claim, reverse, scenario } from "./shared";

const P = "administrator" as const;

export const ADMINISTRATOR_ITEMS: Item[] = [
  claim(P, "fluency",
    "I use AI hands-on in my own leadership work, for analysis, drafting, and planning, with real skill.",
    "confidence"),
  reverse(P, "fluency",
    "I talk about AI institutionally far more than I have ever seriously used it myself.",
    "agreement", "underexposure_fluency"),
  scenario(P, "fluency",
    "You must produce a board-ready analysis of enrollment trends by Friday.", [
      "I delegate it entirely; I would not involve AI myself.",
      "I ask AI to write the analysis from my summary numbers.",
      "I load the data, iterate on the analysis with AI, and sanity-check the story.",
      "I do that, and ask for competing explanations of the trend before choosing one.",
      "I do that, and reproduce the key figures independently before the board sees them.",
    ], "underexposure_fluency",
    { effects: { 5: { verification: 6 } } }),

  claim(P, "agency",
    "AI informs my decisions; accountability and final judgment stay visibly with me.",
    "agreement"),
  reverse(P, "agency",
    "I defer to AI or vendor recommendations on decisions I should own.",
    "frequency", "authority_transfer"),
  scenario(P, "agency",
    "An AI analytics dashboard flags three teachers as underperforming.", [
      "I act on the flags; that is what the system is for.",
      "I mention the flags in their evaluations as supporting data.",
      "I treat the flags as hypotheses and go look at their classes myself.",
      "I do that, and interrogate the metric itself before it touches anyone's file.",
      "I do that, and set a standing rule: no personnel action originates from an unexamined model output.",
    ], "authority_transfer",
    { effects: { 1: { responsibleUse: -8 }, 2: { responsibleUse: -4 } } }),

  claim(P, "amplification",
    "AI improves my strategic thinking: scenarios, second-order effects, and options I had not weighed.",
    "agreement"),
  reverse(P, "amplification",
    "AI produces documents for me, but my actual decisions are unchanged by it.",
    "agreement", "shallow_use"),
  scenario(P, "amplification",
    "You are designing next year's budget under a shortfall.", [
      "I ask AI where schools usually cut and follow the list.",
      "I ask for a cut list that hits my target number.",
      "I model several scenarios with AI and compare the tradeoffs.",
      "I do that, and ask what problems each scenario would create two years from now.",
      "I do that, and use AI to argue against the option I prefer, so I can find my own bias.",
    ], "shallow_use"),

  claim(P, "dependencySafety",
    "My core leadership capabilities, in writing, judgment, and analysis, are intact without AI.",
    "confidence"),
  reverse(P, "dependencySafety",
    "I would struggle to produce my own key documents without AI now.",
    "agreement", "dependency_starting_tasks"),
  scenario(P, "dependencySafety",
    "A crisis communication must go out within the hour, and no AI tool is available.", [
      "I would be in real difficulty, because AI writes those for me.",
      "It would go out rough and late.",
      "It would go out: slower and plainer, but sound.",
      "No issue, because I practise crisis writing myself and keep the skill current.",
      "No issue, and by my own policy the core of crisis communication is drafted by a human anyway.",
    ], "independent_capability_low"),

  claim(P, "verification",
    "Claims that enter institutional decisions, whether from AI or vendors, get verified against primary sources first.",
    "frequency"),
  reverse(P, "verification",
    "Polished AI or vendor material usually goes into my presentations and decisions unchanged.",
    "agreement", "uncritical_acceptance"),
  scenario(P, "verification",
    "A vendor's AI product demo claims a 30 percent learning gain, with a whitepaper attached.", [
      "I cite the gain in my recommendation to the board.",
      "I cite it with 'vendor-reported' attached.",
      "I read the whitepaper before citing anything.",
      "I read it, check the study design, and look for independent replication.",
      "I do that, and pilot with our own students before any such claim reaches the board.",
    ], "verification_low"),

  claim(P, "skillGrowth",
    "AI is raising my own and my organization's capability, not merely our output volume.",
    "agreement"),
  reverse(P, "skillGrowth",
    "We produce more documents since adopting AI, but I could not show that anyone is more capable.",
    "agreement", "skill_erosion"),
  scenario(P, "skillGrowth",
    "A year into AI adoption, you review its effect on your leadership team.", [
      "We adopted it, and that is the result I would report.",
      "Output is up; that is what I report.",
      "I survey the team on time saved and perceived quality.",
      "I look for evidence of capability: better decisions, better analysis, better meetings.",
      "I do that, and where AI replaced growth, such as juniors no longer learning by drafting, I redesign the work.",
    ], "skill_erosion"),

  claim(P, "creativity",
    "AI has opened genuinely new institutional possibilities that we act on, not just faster paperwork.",
    "agreement"),
  reverse(P, "creativity",
    "Our AI use imitates other institutions; nothing original has come out of it.",
    "agreement", "creativity_homogenization"),
  scenario(P, "creativity",
    "You are designing a new program meant to differentiate the institution.", [
      "I ask AI what programs are trending and copy the best fit.",
      "I pick from its list, with local adjustments.",
      "I start from our identity and use AI to expand our own concept.",
      "I do that, and have AI attack the concept hard before we commit.",
      "I do that, and bring faculty into the same AI-assisted design process, so the originality is institutional, not just mine.",
    ], "creativity_homogenization"),

  claim(P, "responsibleUse",
    "I can articulate our data, privacy, and disclosure rules for AI, and I follow them personally.",
    "confidence"),
  reverse(P, "responsibleUse",
    "I put sensitive institutional or personnel information into AI tools that are not approved for it.",
    "frequency", "privacy_risk"),
  scenario(P, "responsibleUse",
    "You want AI help preparing a difficult personnel decision.", [
      "I paste the file in; efficiency matters.",
      "I paste it with the name removed.",
      "I describe the situation abstractly, with no identifiers.",
      "I do that, and only in a tool cleared for confidential use.",
      "I do that, and keep the judgment itself human, with counsel where needed.",
    ], "privacy_risk"),

  claim(P, "transfer",
    "What I work out with AI changes how I lead afterwards, when the tool is not involved.",
    "agreement"),
  reverse(P, "transfer",
    "What comes out of my AI sessions rarely changes how I actually lead.",
    "agreement", "transfer_low"),
  scenario(P, "transfer",
    "AI helped you work out a change-management approach for a difficult rollout. Six months later, a new rollout begins.", [
      "I would start over with AI, from the beginning.",
      "I remember that it worked, not why.",
      "With my notes, I can reapply it.",
      "I know it well enough to apply and adapt it without help.",
      "My team knows it too, because I have taught it to them.",
    ], "transfer_low"),

  claim(P, "adaptability",
    "I re-examine our AI strategy and my own habits on a regular cycle, against evidence.",
    "frequency"),
  reverse(P, "adaptability",
    "Our AI policy has not changed since we first wrote it.",
    "agreement", "workflow_stagnation"),
  scenario(P, "adaptability",
    "A change in what AI tools can do makes part of your AI policy out of date.", [
      "I keep the policy; stability matters most.",
      "I patch quietly when problems surface.",
      "I convene a review when someone raises it.",
      "We have a standing review cycle that catches this.",
      "We have a standing review cycle, we watch for changes coming, and staff know exactly how to report gaps.",
    ], "workflow_stagnation"),
];
