import type { Item } from "../engine/types";
import { claim, reverse, scenario } from "./shared";

const P = "parent" as const;

export const PARENT_ITEMS: Item[] = [
  claim(P, "fluency",
    "I can use AI competently for my own tasks, at work and at home, and I get real value from it.",
    "confidence"),
  reverse(P, "fluency",
    "Most of what I know about AI comes from the news or other people. I have little hands-on experience myself.",
    "agreement", "underexposure_fluency"),
  scenario(P, "fluency",
    "A dense school policy letter or insurance document lands in your inbox and you need to understand it properly.", [
      "I would not think to use AI, or would not know where to start.",
      "I paste it in and read the summary.",
      "I paste it, get a summary, and ask follow-up questions until I actually understand it.",
      "I do that, and also ask what the document does not say that I should be asking about.",
      "I do that, and verify anything consequential with the school or provider directly.",
    ], "underexposure_fluency",
    { effects: { 5: { verification: 6 } } }),

  claim(P, "agency",
    "When AI gives advice on family matters, we make the decision. It is one input, not the answer.",
    "agreement"),
  reverse(P, "agency",
    "I follow AI suggestions on family matters without really weighing them, because it sounds authoritative.",
    "frequency", "authority_transfer"),
  scenario(P, "agency",
    "AI suggests a screen-time plan for your child that conflicts with your instincts.", [
      "I adopt it; it aggregates more knowledge than I have.",
      "I adopt most of it and quietly drop the parts that feel odd.",
      "I compare its reasoning with what I know about my own child.",
      "I do that, and talk it over with my spouse or another parent before deciding.",
      "I treat it as one input; the decision comes from our values, our child, and our judgment.",
    ], "authority_transfer"),

  claim(P, "amplification",
    "AI helps me think through parenting and household decisions more thoroughly: more options, better questions.",
    "agreement"),
  reverse(P, "amplification",
    "AI gives me answers, but I could not say it improves my thinking.",
    "agreement", "shallow_use"),
  scenario(P, "amplification",
    "You are researching schooling options for your child.", [
      "I ask AI which school is best and go with its answer.",
      "I ask for a ranked list and shortlist from it.",
      "I ask for the criteria that matter, then build the comparison myself.",
      "I do that, and ask AI to argue against my current favorite.",
      "I do that, then take those better questions into school visits and conversations with other families.",
    ], "shallow_use",
    { effects: { 1: { agency: -5 } } }),

  claim(P, "dependencySafety",
    "For everyday judgment, whether letters, plans, or decisions, I can still function fully without AI.",
    "confidence"),
  reverse(P, "dependencySafety",
    "I feel a small panic now when I have to draft or decide something without AI.",
    "agreement", "dependency_starting_tasks"),
  scenario(P, "dependencySafety",
    "You must write a sensitive note to your child's teacher, and your usual AI tool is down.", [
      "I would postpone it until the tool is back.",
      "I would write it, but be anxious about the wording the whole time.",
      "Slower, but fine.",
      "No issue; AI polishes my writing, it does not carry it.",
      "No issue, and for sensitive notes I usually write the first draft alone anyway.",
    ], "independent_capability_low"),

  claim(P, "verification",
    "Before acting on an AI claim that affects my family, I check it against a source I trust.",
    "frequency"),
  reverse(P, "verification",
    "If AI states a parenting or safety claim confidently, I generally take it at face value.",
    "agreement", "uncritical_acceptance"),
  scenario(P, "verification",
    "AI tells you about a new safety concern with an app your child uses, citing a report.", [
      "I delete the app tonight and warn the other parents.",
      "I warn the other parents now and check the details later.",
      "I look for the report before acting on anything.",
      "I find the report and one independent source, then act.",
      "I do that, and I talk with my child to see what is actually happening in their use of it.",
    ], "verification_low",
    { effects: { 5: { responsibleUse: 5 } } }),

  claim(P, "skillGrowth",
    "AI is adding real capabilities to our household; I can do things now that I could not do before.",
    "agreement"),
  reverse(P, "skillGrowth",
    "I have handed skills over to AI that I would rather have kept, such as writing, planning, or figuring things out.",
    "agreement", "skill_erosion"),
  scenario(P, "skillGrowth",
    "A task you always did yourself, such as the family budget or trip planning, has quietly become something AI does for you.", [
      "That suits me. Handing that task over is exactly what I wanted.",
      "I had not noticed, and I would find it hard to take the task back now.",
      "I could take it back with some effort.",
      "I stay in the loop deliberately; AI assists, I still drive it.",
      "I use the saved time on things I chose, and I keep a hand in the task so the skill stays mine.",
    ], "skill_erosion"),

  claim(P, "creativity",
    "AI expands what our family creates and explores together, from projects to trips to traditions.",
    "frequency"),
  reverse(P, "creativity",
    "We use AI only to get tasks done. It has not led us to try anything new.",
    "agreement", "creativity_homogenization"),
  scenario(P, "creativity",
    "You are planning a birthday or family celebration.", [
      "I ask AI for a complete plan and execute it.",
      "I pick from its list of themes.",
      "I start from what my child loves and use AI to extend it.",
      "I do that, and deliberately push past its first generic suggestions.",
      "I make it a game we play together: our ideas, its twists, and the child chooses and remixes.",
    ], "creativity_homogenization"),

  claim(P, "responsibleUse",
    "I have explicit boundaries about family information in AI tools, and I keep them.",
    "confidence"),
  reverse(P, "responsibleUse",
    "I share details about my children with AI tools without much thought.",
    "frequency", "privacy_risk"),
  scenario(P, "responsibleUse",
    "You want AI advice about a recurring conflict with your child.", [
      "I describe everything: name, school, the full history.",
      "I tell the whole story with the name changed.",
      "I describe the pattern without any identifying details.",
      "I do that, and I check what the tool retains before having deep conversations with it.",
      "I do that, and for the deepest issues I choose a human, whether spouse, mentor, or counselor, rather than the tool.",
    ], "privacy_risk"),

  claim(P, "transfer",
    "What I learn through AI becomes mine; I can use it and explain it later without the tool.",
    "confidence"),
  reverse(P, "transfer",
    "Things I learn with AI's help do not stay with me afterwards.",
    "agreement", "transfer_low"),
  scenario(P, "transfer",
    "You used AI to understand the method behind your child's math homework. Two weeks later, they ask for help again.", [
      "I would start over with AI, from the beginning.",
      "I recall the name of the method, nothing more.",
      "With a peek at my notes, I can help.",
      "I can help cold; the method became mine.",
      "I can help, and I can show them how to learn it the way I did, checks included.",
    ], "transfer_low"),

  claim(P, "adaptability",
    "I keep updating how our family handles AI as the tools change and my children grow.",
    "frequency"),
  reverse(P, "adaptability",
    "We set our family's AI rules once and have not revisited them.",
    "agreement", "workflow_stagnation"),
  scenario(P, "adaptability",
    "Your child starts using an AI tool you have never seen before.", [
      "I ban it until I hear otherwise.",
      "I allow it; kids understand these things better than I do.",
      "I ask them to show me how it works.",
      "I try it myself, then we set expectations together.",
      "I do that, and we revisit the agreement after a month of actual use.",
    ], "workflow_stagnation"),
];
