import type { Item } from "../engine/types";
import { claim, reverse, scenario } from "./shared";

/**
 * The Professional set.
 *
 * The catch-all: anyone whose work is not a classroom, a congregation, a
 * household or a business they own. It asks about the AI in a working life and
 * the AI in the rest of it, because for most people those are the same tools an
 * hour apart, and a set that only asked about the office would miss half of
 * what is forming them.
 *
 * Ten constructs, one claim, one reverse item and one real situation each, on
 * the same scoring, the same gates and the same route as every other set.
 * Nothing here is specific to a sector, a rank or a qualification.
 */

const P = "professional" as const;

export const PROFESSIONAL_ITEMS: Item[] = [
  claim(P, "fluency",
    "I use AI hands-on in my own work, often enough to know from experience where it is reliable and where it quietly is not.",
    "confidence",
    { why: "Fluency is not enthusiasm and it is not avoidance. It is knowing, from use, where a tool is reliable and where it quietly is not. This reading separates people who have opinions about AI from people who have experience of it." }),
  reverse(P, "fluency",
    "I hold firm views about AI that are well ahead of how much I have actually used it.",
    "agreement", "underexposure_fluency",
    { why: "Strong views formed at a distance are one of the two ways this assessment sees underexposure. The other is never having tried. Both leave you deciding about something you have not handled." }),
  scenario(P, "fluency",
    "Something lands on you that you have never done before. It is due tomorrow, nobody around you has done it either, and you have about two hours.", [
      "I avoid AI and work it out the long way, whatever that costs.",
      "I ask AI for the answer and use what comes back.",
      "I ask AI to explain the shape of the task, then do it myself with that map.",
      "I do that, and check the map against one source the tool did not give me.",
      "I do that, and keep a short note of what I learned so the next one is unaided.",
    ], "underexposure_fluency",
    { why: "A task you have never done before is where fluency shows. The question is not whether you use the tool, but whether you come out of it able to do the next one.",
      effects: { 5: { transfer: 6 } } }),

  claim(P, "agency",
    "AI informs what I do, and the decision and the responsibility for it visibly stay with me.",
    "agreement",
    { why: "Agency is who is actually deciding. AI can inform a decision without taking it, but that line moves quietly, and it usually moves when you are busy rather than when you are thinking about it." }),
  reverse(P, "agency",
    "I go along with what AI suggests even when something about it does not sit right with me.",
    "frequency", "authority_transfer",
    { why: "Overriding your own unease is the moment agency transfers. Most people can name a time they did it. How often it happens is the reading." }),
  scenario(P, "agency",
    "You need to send a message that settles something contested, with a colleague or at home. AI drafts it, and the draft is better written than anything you would have produced.", [
      "I send it. It says it better than I would have.",
      "I change a few words and send it.",
      "I use its structure but write the substance in my own words.",
      "I do that, and cut anything I would not defend if I were asked about it later.",
      "I do that, and ask myself first whether this is a message I should be writing rather than drafting.",
    ], "authority_transfer",
    { why: "A message that settles something contested is a decision, not a document. What you do here shows whether the tool is helping you say what you mean, or saying it for you.",
      effects: { 1: { responsibleUse: -6 } } }),

  claim(P, "amplification",
    "AI improves my thinking rather than only my output: I end up seeing angles I would have missed on my own.",
    "agreement",
    { why: "The claim this instrument tests is that AI can make output better while leaving thinking untouched. Amplification is the case where it genuinely does the other thing." }),
  reverse(P, "amplification",
    "AI produces more for me, but what I actually think about my work has not changed because of it.",
    "agreement", "shallow_use",
    { why: "More output with unchanged thinking is the most common shape of AI use, and the least visible. Nothing about it feels like a problem while it is happening." }),
  scenario(P, "amplification",
    "You are weighing a decision that will actually cost something whichever way it goes: a job, a move, a budget, a commitment. There is no obviously right answer.", [
      "I do not involve AI in decisions like that.",
      "I ask it what it would do and weigh that heavily.",
      "I ask it to lay out the options and the trade-offs, then decide myself.",
      "I do that, and ask it to argue against the option I am leaning towards.",
      "I do that, and write my own reasoning down before I read its version of it.",
    ], "shallow_use",
    { why: "A real decision with real trade-offs is where amplification either shows up or does not. Using AI to argue against yourself is a different act from using it to agree with you.",
      effects: { 5: { agency: 5 } } }),

  claim(P, "dependencySafety",
    "If every AI tool disappeared tomorrow, I could still do the core of my work to the standard it needs.",
    "confidence",
    { why: "This is the question the whole assessment is built around. Not whether you use AI, but what is left when it is gone. It is scored as protection, not as abstinence." }),
  reverse(P, "dependencySafety",
    "There are tasks I now start by opening AI, because I am no longer sure how to begin them without it.",
    "agreement", "dependency_starting_tasks",
    { why: "Not knowing how to begin is different from choosing not to. This item is looking for the tasks where the starting point itself has been outsourced." }),
  scenario(P, "dependencySafety",
    "Your usual AI tool is unavailable for a week. There is no substitute you can get access to, and your workload has not changed.", [
      "The work stops or slips badly. There is no version of it without the tool.",
      "I get through it, much slower, and the quality drops.",
      "I get through it at close to normal quality, slower.",
      "I get through it at normal quality; the tool saves me time rather than carrying me.",
      "I get through it, and notice which habits had quietly become dependencies.",
    ], "independent_capability_low",
    { why: "A week without the tool is the cleanest test of dependence there is. Everyone slows down; the reading is what happens to the quality and whether the work still exists." }),

  claim(P, "verification",
    "Before I act on something AI told me, I check it against a source the tool did not supply.",
    "frequency",
    { why: "Verification is checking somewhere the tool did not supply. Asking the same tool whether it was right is not a check, because it will usually say yes." }),
  reverse(P, "verification",
    "If an AI answer sounds right and is well written, I usually take it as correct without checking.",
    "agreement", "uncritical_acceptance",
    { why: "Fluent, confident and well formatted is exactly what an inaccurate answer looks like. This item asks whether presentation is doing your checking for you." }),
  scenario(P, "verification",
    "AI gives you a specific figure, a date, or a rule. It sounds authoritative, you have no immediate reason to doubt it, and you are about to act on it.", [
      "I use it. It is usually right.",
      "I skim it for anything that looks obviously wrong.",
      "I check it against one independent source before I use it.",
      "I do that, and check twice when the cost of being wrong is high.",
      "I do that, and I can tell you which claims I checked and which I did not.",
    ], "verification_low",
    { why: "A figure, a date or a rule is where an unchecked answer does real damage. What matters is not that you check everything, but that you know which ones you checked.",
      effects: { 1: { responsibleUse: -8 }, 2: { responsibleUse: -4 } } }),

  claim(P, "skillGrowth",
    "I am better at my work than I was a year ago, in ways that would show even with no AI in the room.",
    "agreement",
    { why: "Skill growth is improvement that would show without the tool. It is possible for output to rise for two years while the underlying skill does not move at all." }),
  reverse(P, "skillGrowth",
    "What I produce has improved, but the skill underneath it has not moved with it.",
    "agreement", "skill_erosion",
    { why: "This is the gap between what you can produce and what you can do. When they separate, the production usually hides it." }),
  scenario(P, "skillGrowth",
    "There is something you used to be good at that AI now does for you every time: writing a certain kind of thing, working something out, remembering how something is done.", [
      "I have not thought about it. The tool does it, so I do not.",
      "I have noticed the skill fading and accepted it.",
      "I keep my hand in occasionally so it does not go entirely.",
      "I practise it deliberately, unaided, on a schedule I actually keep.",
      "I do that, and I have decided which skills I am willing to let go and which I am not.",
    ], "skill_erosion",
    { why: "Some skills are worth letting go and some are not. This item is less about which you chose than about whether you chose at all." }),

  claim(P, "creativity",
    "What I make with AI still sounds like me, rather than like everything else the tool produces.",
    "agreement",
    { why: "Creative leverage is whether the tool widens what you make or narrows it towards a standard shape. Both happen, and the narrowing is harder to notice from inside." }),
  reverse(P, "creativity",
    "My work has flattened towards a standard AI voice, and I had stopped noticing until now.",
    "agreement", "creativity_homogenization",
    { why: "Flattening is gradual. It shows first in the things you no longer bother to say differently." }),
  scenario(P, "creativity",
    "You need an idea rather than a document. There is no template for this one, and the obvious approaches have already been tried.", [
      "I ask AI for ideas and pick from its list.",
      "I ask AI for ideas and adapt the best one.",
      "I write down my own ideas first, then ask AI to widen the field.",
      "I do that, and use it to attack my ideas rather than to replace them.",
      "I do that, and keep the ideas that are mine even when its version is smoother.",
    ], "creativity_homogenization",
    { why: "Where you put your own thinking in the order of operations decides whether the tool extends your range or replaces it.",
      effects: { 3: { agency: 4 }, 4: { agency: 5 } } }),

  claim(P, "responsibleUse",
    "I know what I will and will not put into an AI tool, and I hold that line when I am under time pressure.",
    "confidence",
    { why: "Responsible use is a line you hold when it is inconvenient. Everyone has one in principle; this asks whether yours survives a deadline." }),
  reverse(P, "responsibleUse",
    "I have pasted something into AI that I would not want the person it concerns to know I had pasted.",
    "frequency", "privacy_risk",
    { why: "Most people have done this once. The reading is frequency, and this item is scored gently: an honest answer is worth more here than a careful one." }),
  scenario(P, "responsibleUse",
    "The fastest way through a problem involves pasting in something confidential about another person: a health matter, a complaint, a performance issue, a family situation.", [
      "I paste it. It saves real time and nothing has ever gone wrong.",
      "I paste it and take the name off.",
      "I remove enough that the person could not be identified, and check that I have.",
      "I use a tool approved for that kind of information, or I do it without AI.",
      "I do that, and I could explain my rule to the person concerned without embarrassment.",
    ], "privacy_risk",
    { why: "Information about another person is the case where the cost of being wrong falls on someone who did not choose the tool.",
      effects: { 1: { agency: -6 } } }),

  claim(P, "transfer",
    "What I learn with AI stays with me: I could do the same thing again weeks later without the tool.",
    "agreement",
    { why: "Transfer is whether an AI assisted solution becomes something you can do. Without it, every similar problem starts from zero and needs the tool again." }),
  reverse(P, "transfer",
    "I have solved things with AI that I could not have solved again on my own a week later.",
    "frequency", "transfer_low",
    { why: "Solving something you could not solve again is the clearest signal that the work happened beside you rather than in you." }),
  scenario(P, "transfer",
    "AI walks you through something you did not know how to do, step by step, and it works first time. You have the result and about ten minutes before the next thing.", [
      "I move on. It worked, and that is what mattered.",
      "I save the answer in case it comes up again.",
      "I read back through it so I understand why it worked.",
      "I close the tool and reconstruct the method in my own words.",
      "I do that, and do the next one of its kind unaided to see whether it stuck.",
    ], "transfer_low",
    { why: "What you do in the ten minutes after it works is what decides whether you keep it. Reading the answer back is not the same as reconstructing it, and reconstructing it is not the same as doing the next one alone.",
      effects: { 4: { skillGrowth: 5 }, 5: { skillGrowth: 6 } } }),

  claim(P, "adaptability",
    "I review how I use AI and change it on purpose, rather than drifting along with whatever is new.",
    "agreement",
    { why: "Adaptive growth is reviewing your own practice on purpose. It is the dimension that keeps every other one current as the tools keep changing." }),
  reverse(P, "adaptability",
    "I use AI in much the same way I did when I started, out of habit rather than because I decided to.",
    "agreement", "workflow_stagnation",
    { why: "Using AI the way you did on day one is not stability, it is drift. The tools moved; the habits did not." }),
  scenario(P, "adaptability",
    "The tools change again. Something you had come to rely on now behaves differently, and the work you did with the old behaviour is still out there.", [
      "I carry on as before until it breaks properly.",
      "I adjust when I have to, not before.",
      "I test what changed on a task that does not matter, then adapt.",
      "I do that, and re-check the work I had trusted to the old behaviour.",
      "I do that, and treat reviewing my own habits as a standing part of the work.",
    ], "workflow_stagnation",
    { why: "A tool that changes underneath you is the moment to re-examine what you had trusted to its old behaviour." }),
];
