import type { Item } from "../engine/types";
import { claim, reverse, scenario } from "./shared";

const P = "teacher" as const;

export const TEACHER_ITEMS: Item[] = [
  claim(P, "fluency",
    "I can get AI to produce genuinely usable teaching materials by supplying my objectives, constraints, and examples of my standard.",
    "confidence"),
  reverse(P, "fluency",
    "My AI use is limited to one simple pattern, such as asking it to write something and taking what comes.",
    "frequency", "underexposure_fluency"),
  scenario(P, "fluency",
    "You need a differentiated activity for a mixed-ability class, and the AI's first version is generic.", [
      "I use it as it is, because I need something ready tonight.",
      "I ask again with 'make this better' and take the second version.",
      "I feed it my class profile and regenerate until it fits.",
      "I decompose it: core task, extensions, and supports requested separately, then assembled.",
      "I assemble it that way, then trial it against my own past materials before it reaches students.",
    ], "underexposure_fluency",
    { effects: { 5: { verification: 6 } } }),

  claim(P, "agency",
    "AI can draft, but what my students actually receive reflects my pedagogical decisions.",
    "agreement"),
  reverse(P, "agency",
    "I hand instructional decisions such as pacing, grouping, or grading judgment to AI recommendations without weighing them myself.",
    "frequency", "authority_transfer"),
  scenario(P, "agency",
    "AI proposes reordering your unit and cutting a lesson you consider formative.", [
      "I adopt it, on the basis that it has been trained on far more curricula than I have seen.",
      "I adopt most of it and drop the parts that feel wrong.",
      "I compare its rationale with mine before deciding anything.",
      "I take its rationale as a challenge, re-argue my own design, and keep what survives.",
      "I do that, and note where its reasoning exposed a real weakness, so the unit improves on my terms.",
    ], "authority_transfer"),

  claim(P, "amplification",
    "AI improves how I think about teaching: it points out misconceptions, alternative explanations, and gaps in my lessons.",
    "agreement"),
  reverse(P, "amplification",
    "AI mostly saves me typing; it rarely changes how I think about a lesson.",
    "agreement", "shallow_use"),
  scenario(P, "amplification",
    "Half the class missed the same quiz question.", [
      "I ask AI to write a re-teach worksheet.",
      "I ask AI why students miss questions like this and use its list.",
      "I give AI the actual wrong answers and ask what misconception they share.",
      "I do that, then have it generate probes to test which misconception each group holds.",
      "I do that, then practise my new explanation with AI acting as a confused student, to find where it falls down.",
    ], "shallow_use",
    { effects: { 5: { transfer: 5 } } }),

  claim(P, "dependencySafety",
    "Without AI, I could still plan a strong week of lessons at close to my usual quality.",
    "confidence"),
  reverse(P, "dependencySafety",
    "I can no longer start planning until I have an AI draft in front of me.",
    "frequency", "dependency_starting_tasks"),
  scenario(P, "dependencySafety",
    "The internet is down during your planning period, the day before an observed lesson.", [
      "I would be in real trouble; my plans come from AI now.",
      "I would produce something, but well below my recent standard.",
      "Slower and plainer, but a sound lesson would exist by the end.",
      "Little difference; AI accelerates what I can already build from scratch.",
      "No difference, and I deliberately plan some lessons unaided to keep it that way.",
    ], "independent_capability_low"),

  claim(P, "verification",
    "I verify AI-generated content, including facts, sources, and solution steps, before any of it reaches students.",
    "frequency"),
  reverse(P, "verification",
    "If AI material looks professional and well formatted, I use it in class without checking it.",
    "agreement", "uncritical_acceptance"),
  scenario(P, "verification",
    "AI produces a beautiful reading passage with historical details and a quotation, ready to print.", [
      "I print it; it reads perfectly.",
      "I fix anything that jumps out on a quick read-through.",
      "I check the quotation before printing.",
      "I check the quotation and every fact a student could later repeat.",
      "I verify all of it and keep the record, because students will cite this material for weeks.",
    ], "verification_low"),

  claim(P, "skillGrowth",
    "The time AI saves me goes into higher-value teaching, and my own craft keeps growing.",
    "agreement"),
  reverse(P, "skillGrowth",
    "Skills I trained for years, like writing feedback or designing assessments, feel like they are fading under AI.",
    "agreement", "skill_erosion"),
  scenario(P, "skillGrowth",
    "You realize you have not written a single piece of student feedback yourself this term.", [
      "Good; that is exactly what the tool is for.",
      "Slightly uneasy, but the comments read fine.",
      "I would alternate: some classes AI-drafted, some fully mine.",
      "I write the first draft myself and use AI to refine it, so I keep the skill in practice.",
      "I put the freed time into the kind of feedback AI cannot give, and I can name what that is.",
    ], "skill_erosion"),

  claim(P, "creativity",
    "I now design activities I would never have attempted before, using AI to extend my own ideas.",
    "frequency"),
  reverse(P, "creativity",
    "The materials I make with AI are starting to look the same as each other.",
    "agreement", "creativity_homogenization"),
  scenario(P, "creativity",
    "You are designing a capstone project from scratch.", [
      "I ask AI for a complete project and adopt it.",
      "I ask for options, pick one, and lightly localize it.",
      "I bring my own concept and use AI to elaborate it.",
      "I bring my concept, have AI attack it, and rebuild it stronger.",
      "I co-develop something genuinely new, and I could tell you which ideas were mine, which were its, and which emerged between us.",
    ], "creativity_homogenization"),

  claim(P, "responsibleUse",
    "I have clear personal rules for student data and AI: what I will never paste into a tool, and why.",
    "confidence"),
  reverse(P, "responsibleUse",
    "I paste student work, names, or grades into AI tools without thinking much about it.",
    "frequency", "privacy_risk"),
  scenario(P, "responsibleUse",
    "You want AI feedback on a struggling student's essay, and the essay includes personal details about the student's family.", [
      "I paste it as it is; the tool is just a tool.",
      "I remove the student's name and paste the rest.",
      "I remove the name and the identifying details before pasting.",
      "I strip identity and check the tool's data policy first.",
      "I strip identity, check the policy, and follow my school's rule; if no rule exists, I raise that gap.",
    ], "privacy_risk"),

  claim(P, "transfer",
    "What I learn through AI, whether content or method, sticks; I can teach it later without the tool.",
    "confidence"),
  reverse(P, "transfer",
    "I have to ask AI to explain the same things again, because the explanations do not stay with me.",
    "agreement", "transfer_low"),
  scenario(P, "transfer",
    "AI taught you a new instructional strategy last month. A colleague asks you to explain it.", [
      "I would forward them the chat.",
      "I remember the gist, but not enough to teach it.",
      "I can explain it with my notes open.",
      "I can teach it cold; I ran it in class and it is mine now.",
      "I can teach it, including where AI's version needed adapting for real students.",
    ], "transfer_low"),

  claim(P, "adaptability",
    "I periodically audit my AI habits against student outcomes, not just my own convenience.",
    "frequency"),
  reverse(P, "adaptability",
    "My AI workflow has not changed since I first found one that worked.",
    "agreement", "workflow_stagnation"),
  scenario(P, "adaptability",
    "Your go-to AI workflow starts producing noticeably weaker materials after a model update.", [
      "I keep using it; switching costs time I do not have.",
      "I complain and go back to doing everything manually.",
      "I tinker until the output recovers.",
      "I re-evaluate the available tools and rebuild the workflow.",
      "I rebuild it and document what changed for my department.",
    ], "workflow_stagnation"),
];
