/**
 * Generates the two reference documents from the code that defines them, so
 * neither can drift from what the report actually does. Run with
 * `npx tsx scripts/gen-org-docs.ts`.
 */
import fs from 'fs';
import path from 'path';
import { DIMENSIONS, COMPOSITES, aliasesFor } from '../src/engine/dictionary';
import { CONSTRUCT_IDS, type ConstructId } from '../src/engine/types';
import { STAGES, SCORING, GROUP, CONTINUUM, VERSIONS, CONSTRUCTS } from '../src/engine/config';
import { SUPPRESSION, INFERENCE_FLOOR } from '../src/engine/group';
import { STAGE_BUSINESS } from '../src/engine/orgStageCopy';
import { ARCHETYPES } from '../src/engine/archetypes';
import { PATTERN_RULES } from '../src/engine/patterns';
import { MEASUREMENT_MODULES } from '../src/engine/orgAnalytics';

const out = path.join(process.cwd(), 'docs', 'organisation-report');
const esc = (s: string) => s.replace(/\|/g, '\\|');

/* ------------------------------------------------------- data dictionary */

const dd: string[] = [
  '# Data dictionary',
  '',
  '> Generated by `scripts/gen-org-docs.ts` from the code that defines these values.',
  '> Do not edit by hand: run the script instead.',
  '',
  `Instrument ${VERSIONS.instrument}, scoring ${VERSIONS.scoring}, scenarios ${VERSIONS.scenario}, language ${VERSIONS.language}.`,
  '',
  '## The ten dimensions',
  '',
  'Every dimension is stored on a 0 to 100 scale on which higher is healthier, without',
  'exception. The reliance construct is stored as Independent Capability; editions that',
  'print it as a risk invert it for display only, and the organisation report does not.',
  '',
  '| Body name | Engine name | Cluster | Direction | Watch | Vulnerability | Strength | Gates | Practice |',
  '|---|---|---|---|---|---|---|---|---|',
  ...CONSTRUCT_IDS.map((id) => {
    const d = DIMENSIONS[id];
    const gates = d.practiceGateRole.length
      ? d.practiceGateRole.map((g) => `stage ${g.stage} at ${g.minimum}`).join('; ') : 'none';
    return `| ${d.executiveName} | ${esc(d.canonicalName)} | ${d.cluster} | ${d.healthyDirection} is healthier `
      + `| ${d.thresholds.watch} | ${d.thresholds.vulnerability} | ${d.thresholds.strength} | ${gates} | \`${d.recommendedPractice}\` |`;
  }),
  '',
  '### What each one measures, and why it matters to an employer',
  '',
  ...CONSTRUCT_IDS.flatMap((id) => {
    const d = DIMENSIONS[id];
    return [
      `**${d.executiveName}**`, '',
      `- Engine name: ${d.canonicalName}`,
      `- Also answers to: ${aliasesFor(id).map((a) => `${a.name} (${a.editions.join(', ')})`).join('; ') || 'nothing else'}`,
      d.exposureLabel ? `- Exposure reported as: ${d.exposureLabel}` : '',
      `- What it measures: ${d.whatItMeasures}`,
      `- Business meaning: ${d.businessMeaning}`,
      `- Strength: ${d.bandCopy.strength}`,
      `- Developing: ${d.bandCopy.developing}`,
      `- Watch: ${d.bandCopy.watch}`,
      `- Related composites: ${d.relatedCompositeIds.join(', ') || 'none'}`,
      '',
    ].filter(Boolean);
  }),
  '## The six composites',
  '',
  '| Id | Body name | The question it answers | Direction |',
  '|---|---|---|---|',
  ...COMPOSITES.map((c) =>
    `| \`${c.id}\` | ${c.executiveName} | ${esc(c.question)} | ${c.healthyDirection} is healthier |`),
  '',
  '## The ten stages',
  '',
  '| Stage | Name | Opens at | Gates it adds | What it means for a business |',
  '|---|---|---|---|---|',
  ...STAGES.map((s) => {
    const gates = s.gates
      ? Object.entries(s.gates).map(([c, v]) => `${DIMENSIONS[c as ConstructId].executiveName} ${v}`).join('; ')
      : 'none';
    const biz = STAGE_BUSINESS.find((b) => b.stage === s.stage);
    return `| ${s.stage} | ${s.name} | index ${s.minIndex} | ${gates} | ${esc(biz?.meansForBusiness ?? '')} |`;
  }),
  '',
  '## The nine profiles',
  '',
  ...ARCHETYPES.map((a) => `- **${a.name}**: ${esc(a.tagline)}`),
  '',
  '## Patterns',
  '',
  `${PATTERN_RULES.length} defined. A pattern scoped to an edition is reported as a share of the`,
  'people who could raise it, never of the whole workforce.',
  '',
  '| Pattern | Kind | Editions that can raise it |',
  '|---|---|---|',
  ...PATTERN_RULES.map((r) =>
    `| ${esc(r.label)} | ${r.kind} | ${r.personas ? r.personas.join(', ') : 'all'} |`),
  '',
  '## Thresholds and cut points',
  '',
  '| Value | Setting | Meaning |',
  '|---|---|---|',
  `| ${SCORING.strengthFloor} | \`SCORING.strengthFloor\` | at or above is a strength |`,
  `| ${SCORING.microWatch} | \`SCORING.microWatch\` | below is watch |`,
  `| ${SCORING.vulnerabilityCeiling} | \`SCORING.vulnerabilityCeiling\` | at or below is vulnerable, in any band |`,
  `| ${GROUP.minimumForReport} | \`GROUP.minimumForReport\` | fewer respondents than this and no report is produced |`,
  `| ${GROUP.strongCaveatBelow} | \`GROUP.strongCaveatBelow\` | below this the cover carries the stronger caveat |`,
  `| ${SUPPRESSION.descriptive} | \`SUPPRESSION.descriptive\` | a segment cut needs this many, and this many left outside it |`,
  `| ${SUPPRESSION.sensitive} | \`SUPPRESSION.sensitive\` | a sensitive cut needs this many. None is collected today. |`,
  `| ${INFERENCE_FLOOR} | \`INFERENCE_FLOOR\` | below this, no confidence intervals and no correlations |`,
  `| ${GROUP.capableIndex} | \`GROUP.capableIndex\` | index at or above counts as capable on the use matrix |`,
  `| ${GROUP.judgmentWatch} | \`GROUP.judgmentWatch\` | judgment below this is the subset to act on first |`,
  `| ${GROUP.movableWithin} | \`GROUP.movableWithin\` | index points from the next stage that count as immediately movable |`,
  `| ${GROUP.nearThreshold} | \`GROUP.nearThreshold\` | points from a band threshold that count as close to it |`,
  `| ${GROUP.twoCampGap} | \`GROUP.twoCampGap\` | empty stages between camps that make it two workforces |`,
  `| ${CONTINUUM.borderlineBand} | \`CONTINUUM.borderlineBand\` | index points from a stage boundary that count as borderline |`,
  '',
  '## What is not collected',
  '',
  'Nothing below is estimated, modelled or inferred, and no figure in the report depends on it.',
  '',
  ...MEASUREMENT_MODULES.map((m) => `- **${m.name}**: ${m.whatItWouldAdd}`),
  '',
];
fs.writeFileSync(path.join(out, 'data-dictionary.md'), dd.join('\n'));
console.log('data-dictionary.md written');
